DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL UNIQUE,
    isAdmin BOOLEAN DEFAULT TRUE
);